/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiR2UploadRouteImport } from './routes/api/r2-upload'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedFollowupsRouteImport } from './routes/_authenticated/followups'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedAiAssistantsRouteImport } from './routes/_authenticated/ai-assistants'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedQuotesIndexRouteImport } from './routes/_authenticated/quotes.index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedEmailsIndexRouteImport } from './routes/_authenticated/emails.index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedContactsIndexRouteImport } from './routes/_authenticated/contacts.index'
import { Route as AuthenticatedCompaniesIndexRouteImport } from './routes/_authenticated/companies.index'
import { Route as ApiGmailSyncRouteImport } from './routes/api/gmail/sync'
import { Route as ApiGmailStatusRouteImport } from './routes/api/gmail/status'
import { Route as ApiGmailSendRouteImport } from './routes/api/gmail/send'
import { Route as ApiGmailRefreshBodyRouteImport } from './routes/api/gmail/refresh-body'
import { Route as ApiGmailDisconnectRouteImport } from './routes/api/gmail/disconnect'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings.users'
import { Route as AuthenticatedSettingsStorageRouteImport } from './routes/_authenticated/settings.storage'
import { Route as AuthenticatedSettingsRolesRouteImport } from './routes/_authenticated/settings.roles'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsPermissionsAuditRouteImport } from './routes/_authenticated/settings.permissions-audit'
import { Route as AuthenticatedSettingsOpenaiRouteImport } from './routes/_authenticated/settings.openai'
import { Route as AuthenticatedSettingsGmailRouteImport } from './routes/_authenticated/settings.gmail'
import { Route as AuthenticatedSettingsDashboardStatusRouteImport } from './routes/_authenticated/settings.dashboard-status'
import { Route as AuthenticatedSettingsAuditRouteImport } from './routes/_authenticated/settings.audit'
import { Route as AuthenticatedSettingsAgentVisibilityRouteImport } from './routes/_authenticated/settings.agent-visibility'
import { Route as AuthenticatedSalesResearchRouteImport } from './routes/_authenticated/sales.research'
import { Route as AuthenticatedQuotesIdRouteImport } from './routes/_authenticated/quotes.$id'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated/leads.$id'
import { Route as AuthenticatedEmailsThreadIdRouteImport } from './routes/_authenticated/emails.$threadId'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers.$id'
import { Route as AuthenticatedContactsIdRouteImport } from './routes/_authenticated/contacts.$id'
import { Route as AuthenticatedCompaniesIdRouteImport } from './routes/_authenticated/companies.$id'
import { Route as ApiPublicGmailCronSyncRouteImport } from './routes/api/public/gmail/cron-sync'
import { Route as ApiGmailOauthStartRouteImport } from './routes/api/gmail/oauth.start'
import { Route as ApiGmailOauthCallbackRouteImport } from './routes/api/gmail/oauth.callback'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiR2UploadRoute = ApiR2UploadRouteImport.update({
  id: '/api/r2-upload',
  path: '/api/r2-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowupsRoute = AuthenticatedFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiAssistantsRoute =
  AuthenticatedAiAssistantsRouteImport.update({
    id: '/ai-assistants',
    path: '/ai-assistants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedQuotesIndexRoute =
  AuthenticatedQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailsIndexRoute =
  AuthenticatedEmailsIndexRouteImport.update({
    id: '/emails/',
    path: '/emails/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsIndexRoute =
  AuthenticatedContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompaniesIndexRoute =
  AuthenticatedCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiGmailSyncRoute = ApiGmailSyncRouteImport.update({
  id: '/api/gmail/sync',
  path: '/api/gmail/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailStatusRoute = ApiGmailStatusRouteImport.update({
  id: '/api/gmail/status',
  path: '/api/gmail/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailSendRoute = ApiGmailSendRouteImport.update({
  id: '/api/gmail/send',
  path: '/api/gmail/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailRefreshBodyRoute = ApiGmailRefreshBodyRouteImport.update({
  id: '/api/gmail/refresh-body',
  path: '/api/gmail/refresh-body',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailDisconnectRoute = ApiGmailDisconnectRouteImport.update({
  id: '/api/gmail/disconnect',
  path: '/api/gmail/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsStorageRoute =
  AuthenticatedSettingsStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsRolesRoute =
  AuthenticatedSettingsRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPermissionsAuditRoute =
  AuthenticatedSettingsPermissionsAuditRouteImport.update({
    id: '/permissions-audit',
    path: '/permissions-audit',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsOpenaiRoute =
  AuthenticatedSettingsOpenaiRouteImport.update({
    id: '/openai',
    path: '/openai',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGmailRoute =
  AuthenticatedSettingsGmailRouteImport.update({
    id: '/gmail',
    path: '/gmail',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDashboardStatusRoute =
  AuthenticatedSettingsDashboardStatusRouteImport.update({
    id: '/dashboard-status',
    path: '/dashboard-status',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAuditRoute =
  AuthenticatedSettingsAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAgentVisibilityRoute =
  AuthenticatedSettingsAgentVisibilityRouteImport.update({
    id: '/agent-visibility',
    path: '/agent-visibility',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSalesResearchRoute =
  AuthenticatedSalesResearchRouteImport.update({
    id: '/sales/research',
    path: '/sales/research',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotesIdRoute = AuthenticatedQuotesIdRouteImport.update({
  id: '/quotes/$id',
  path: '/quotes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailsThreadIdRoute =
  AuthenticatedEmailsThreadIdRouteImport.update({
    id: '/emails/$threadId',
    path: '/emails/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsIdRoute = AuthenticatedContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompaniesIdRoute =
  AuthenticatedCompaniesIdRouteImport.update({
    id: '/companies/$id',
    path: '/companies/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicGmailCronSyncRoute = ApiPublicGmailCronSyncRouteImport.update({
  id: '/api/public/gmail/cron-sync',
  path: '/api/public/gmail/cron-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailOauthStartRoute = ApiGmailOauthStartRouteImport.update({
  id: '/api/gmail/oauth/start',
  path: '/api/gmail/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailOauthCallbackRoute = ApiGmailOauthCallbackRouteImport.update({
  id: '/api/gmail/oauth/callback',
  path: '/api/gmail/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/ai-assistants': typeof AuthenticatedAiAssistantsRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/r2-upload': typeof ApiR2UploadRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/emails/$threadId': typeof AuthenticatedEmailsThreadIdRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/quotes/$id': typeof AuthenticatedQuotesIdRoute
  '/sales/research': typeof AuthenticatedSalesResearchRoute
  '/settings/agent-visibility': typeof AuthenticatedSettingsAgentVisibilityRoute
  '/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/settings/dashboard-status': typeof AuthenticatedSettingsDashboardStatusRoute
  '/settings/gmail': typeof AuthenticatedSettingsGmailRoute
  '/settings/openai': typeof AuthenticatedSettingsOpenaiRoute
  '/settings/permissions-audit': typeof AuthenticatedSettingsPermissionsAuditRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/storage': typeof AuthenticatedSettingsStorageRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/api/gmail/disconnect': typeof ApiGmailDisconnectRoute
  '/api/gmail/refresh-body': typeof ApiGmailRefreshBodyRoute
  '/api/gmail/send': typeof ApiGmailSendRoute
  '/api/gmail/status': typeof ApiGmailStatusRoute
  '/api/gmail/sync': typeof ApiGmailSyncRoute
  '/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/contacts/': typeof AuthenticatedContactsIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/emails/': typeof AuthenticatedEmailsIndexRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/quotes/': typeof AuthenticatedQuotesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/gmail/oauth/callback': typeof ApiGmailOauthCallbackRoute
  '/api/gmail/oauth/start': typeof ApiGmailOauthStartRoute
  '/api/public/gmail/cron-sync': typeof ApiPublicGmailCronSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/ai-assistants': typeof AuthenticatedAiAssistantsRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/followups': typeof AuthenticatedFollowupsRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/r2-upload': typeof ApiR2UploadRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/emails/$threadId': typeof AuthenticatedEmailsThreadIdRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/quotes/$id': typeof AuthenticatedQuotesIdRoute
  '/sales/research': typeof AuthenticatedSalesResearchRoute
  '/settings/agent-visibility': typeof AuthenticatedSettingsAgentVisibilityRoute
  '/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/settings/dashboard-status': typeof AuthenticatedSettingsDashboardStatusRoute
  '/settings/gmail': typeof AuthenticatedSettingsGmailRoute
  '/settings/openai': typeof AuthenticatedSettingsOpenaiRoute
  '/settings/permissions-audit': typeof AuthenticatedSettingsPermissionsAuditRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/storage': typeof AuthenticatedSettingsStorageRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/api/gmail/disconnect': typeof ApiGmailDisconnectRoute
  '/api/gmail/refresh-body': typeof ApiGmailRefreshBodyRoute
  '/api/gmail/send': typeof ApiGmailSendRoute
  '/api/gmail/status': typeof ApiGmailStatusRoute
  '/api/gmail/sync': typeof ApiGmailSyncRoute
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/contacts': typeof AuthenticatedContactsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/emails': typeof AuthenticatedEmailsIndexRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/quotes': typeof AuthenticatedQuotesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/api/gmail/oauth/callback': typeof ApiGmailOauthCallbackRoute
  '/api/gmail/oauth/start': typeof ApiGmailOauthStartRoute
  '/api/public/gmail/cron-sync': typeof ApiPublicGmailCronSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/ai-assistants': typeof AuthenticatedAiAssistantsRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/followups': typeof AuthenticatedFollowupsRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/api/r2-upload': typeof ApiR2UploadRoute
  '/_authenticated/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/_authenticated/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/emails/$threadId': typeof AuthenticatedEmailsThreadIdRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/quotes/$id': typeof AuthenticatedQuotesIdRoute
  '/_authenticated/sales/research': typeof AuthenticatedSalesResearchRoute
  '/_authenticated/settings/agent-visibility': typeof AuthenticatedSettingsAgentVisibilityRoute
  '/_authenticated/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/_authenticated/settings/dashboard-status': typeof AuthenticatedSettingsDashboardStatusRoute
  '/_authenticated/settings/gmail': typeof AuthenticatedSettingsGmailRoute
  '/_authenticated/settings/openai': typeof AuthenticatedSettingsOpenaiRoute
  '/_authenticated/settings/permissions-audit': typeof AuthenticatedSettingsPermissionsAuditRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/_authenticated/settings/storage': typeof AuthenticatedSettingsStorageRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/api/gmail/disconnect': typeof ApiGmailDisconnectRoute
  '/api/gmail/refresh-body': typeof ApiGmailRefreshBodyRoute
  '/api/gmail/send': typeof ApiGmailSendRoute
  '/api/gmail/status': typeof ApiGmailStatusRoute
  '/api/gmail/sync': typeof ApiGmailSyncRoute
  '/_authenticated/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/_authenticated/contacts/': typeof AuthenticatedContactsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/emails/': typeof AuthenticatedEmailsIndexRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/quotes/': typeof AuthenticatedQuotesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/gmail/oauth/callback': typeof ApiGmailOauthCallbackRoute
  '/api/gmail/oauth/start': typeof ApiGmailOauthStartRoute
  '/api/public/gmail/cron-sync': typeof ApiPublicGmailCronSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/activity'
    | '/ai-assistant'
    | '/ai-assistants'
    | '/calls'
    | '/dashboard'
    | '/documents'
    | '/followups'
    | '/meetings'
    | '/settings'
    | '/tasks'
    | '/api/r2-upload'
    | '/companies/$id'
    | '/contacts/$id'
    | '/customers/$id'
    | '/emails/$threadId'
    | '/leads/$id'
    | '/projects/$id'
    | '/quotes/$id'
    | '/sales/research'
    | '/settings/agent-visibility'
    | '/settings/audit'
    | '/settings/dashboard-status'
    | '/settings/gmail'
    | '/settings/openai'
    | '/settings/permissions-audit'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/storage'
    | '/settings/users'
    | '/api/gmail/disconnect'
    | '/api/gmail/refresh-body'
    | '/api/gmail/send'
    | '/api/gmail/status'
    | '/api/gmail/sync'
    | '/companies/'
    | '/contacts/'
    | '/customers/'
    | '/emails/'
    | '/leads/'
    | '/projects/'
    | '/quotes/'
    | '/settings/'
    | '/api/gmail/oauth/callback'
    | '/api/gmail/oauth/start'
    | '/api/public/gmail/cron-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/activity'
    | '/ai-assistant'
    | '/ai-assistants'
    | '/calls'
    | '/dashboard'
    | '/documents'
    | '/followups'
    | '/meetings'
    | '/tasks'
    | '/api/r2-upload'
    | '/companies/$id'
    | '/contacts/$id'
    | '/customers/$id'
    | '/emails/$threadId'
    | '/leads/$id'
    | '/projects/$id'
    | '/quotes/$id'
    | '/sales/research'
    | '/settings/agent-visibility'
    | '/settings/audit'
    | '/settings/dashboard-status'
    | '/settings/gmail'
    | '/settings/openai'
    | '/settings/permissions-audit'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/storage'
    | '/settings/users'
    | '/api/gmail/disconnect'
    | '/api/gmail/refresh-body'
    | '/api/gmail/send'
    | '/api/gmail/status'
    | '/api/gmail/sync'
    | '/companies'
    | '/contacts'
    | '/customers'
    | '/emails'
    | '/leads'
    | '/projects'
    | '/quotes'
    | '/settings'
    | '/api/gmail/oauth/callback'
    | '/api/gmail/oauth/start'
    | '/api/public/gmail/cron-sync'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/activity'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/ai-assistants'
    | '/_authenticated/calls'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/followups'
    | '/_authenticated/meetings'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/api/r2-upload'
    | '/_authenticated/companies/$id'
    | '/_authenticated/contacts/$id'
    | '/_authenticated/customers/$id'
    | '/_authenticated/emails/$threadId'
    | '/_authenticated/leads/$id'
    | '/_authenticated/projects/$id'
    | '/_authenticated/quotes/$id'
    | '/_authenticated/sales/research'
    | '/_authenticated/settings/agent-visibility'
    | '/_authenticated/settings/audit'
    | '/_authenticated/settings/dashboard-status'
    | '/_authenticated/settings/gmail'
    | '/_authenticated/settings/openai'
    | '/_authenticated/settings/permissions-audit'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/roles'
    | '/_authenticated/settings/storage'
    | '/_authenticated/settings/users'
    | '/api/gmail/disconnect'
    | '/api/gmail/refresh-body'
    | '/api/gmail/send'
    | '/api/gmail/status'
    | '/api/gmail/sync'
    | '/_authenticated/companies/'
    | '/_authenticated/contacts/'
    | '/_authenticated/customers/'
    | '/_authenticated/emails/'
    | '/_authenticated/leads/'
    | '/_authenticated/projects/'
    | '/_authenticated/quotes/'
    | '/_authenticated/settings/'
    | '/api/gmail/oauth/callback'
    | '/api/gmail/oauth/start'
    | '/api/public/gmail/cron-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiR2UploadRoute: typeof ApiR2UploadRoute
  ApiGmailDisconnectRoute: typeof ApiGmailDisconnectRoute
  ApiGmailRefreshBodyRoute: typeof ApiGmailRefreshBodyRoute
  ApiGmailSendRoute: typeof ApiGmailSendRoute
  ApiGmailStatusRoute: typeof ApiGmailStatusRoute
  ApiGmailSyncRoute: typeof ApiGmailSyncRoute
  ApiGmailOauthCallbackRoute: typeof ApiGmailOauthCallbackRoute
  ApiGmailOauthStartRoute: typeof ApiGmailOauthStartRoute
  ApiPublicGmailCronSyncRoute: typeof ApiPublicGmailCronSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2-upload': {
      id: '/api/r2-upload'
      path: '/api/r2-upload'
      fullPath: '/api/r2-upload'
      preLoaderRoute: typeof ApiR2UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/followups': {
      id: '/_authenticated/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof AuthenticatedFollowupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-assistants': {
      id: '/_authenticated/ai-assistants'
      path: '/ai-assistants'
      fullPath: '/ai-assistants'
      preLoaderRoute: typeof AuthenticatedAiAssistantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/quotes/': {
      id: '/_authenticated/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AuthenticatedQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emails/': {
      id: '/_authenticated/emails/'
      path: '/emails'
      fullPath: '/emails/'
      preLoaderRoute: typeof AuthenticatedEmailsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/': {
      id: '/_authenticated/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthenticatedContactsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies/': {
      id: '/_authenticated/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthenticatedCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/gmail/sync': {
      id: '/api/gmail/sync'
      path: '/api/gmail/sync'
      fullPath: '/api/gmail/sync'
      preLoaderRoute: typeof ApiGmailSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail/status': {
      id: '/api/gmail/status'
      path: '/api/gmail/status'
      fullPath: '/api/gmail/status'
      preLoaderRoute: typeof ApiGmailStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail/send': {
      id: '/api/gmail/send'
      path: '/api/gmail/send'
      fullPath: '/api/gmail/send'
      preLoaderRoute: typeof ApiGmailSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail/refresh-body': {
      id: '/api/gmail/refresh-body'
      path: '/api/gmail/refresh-body'
      fullPath: '/api/gmail/refresh-body'
      preLoaderRoute: typeof ApiGmailRefreshBodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail/disconnect': {
      id: '/api/gmail/disconnect'
      path: '/api/gmail/disconnect'
      fullPath: '/api/gmail/disconnect'
      preLoaderRoute: typeof ApiGmailDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/storage': {
      id: '/_authenticated/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof AuthenticatedSettingsStorageRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/permissions-audit': {
      id: '/_authenticated/settings/permissions-audit'
      path: '/permissions-audit'
      fullPath: '/settings/permissions-audit'
      preLoaderRoute: typeof AuthenticatedSettingsPermissionsAuditRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/openai': {
      id: '/_authenticated/settings/openai'
      path: '/openai'
      fullPath: '/settings/openai'
      preLoaderRoute: typeof AuthenticatedSettingsOpenaiRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/gmail': {
      id: '/_authenticated/settings/gmail'
      path: '/gmail'
      fullPath: '/settings/gmail'
      preLoaderRoute: typeof AuthenticatedSettingsGmailRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/dashboard-status': {
      id: '/_authenticated/settings/dashboard-status'
      path: '/dashboard-status'
      fullPath: '/settings/dashboard-status'
      preLoaderRoute: typeof AuthenticatedSettingsDashboardStatusRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/audit': {
      id: '/_authenticated/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AuthenticatedSettingsAuditRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/agent-visibility': {
      id: '/_authenticated/settings/agent-visibility'
      path: '/agent-visibility'
      fullPath: '/settings/agent-visibility'
      preLoaderRoute: typeof AuthenticatedSettingsAgentVisibilityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/sales/research': {
      id: '/_authenticated/sales/research'
      path: '/sales/research'
      fullPath: '/sales/research'
      preLoaderRoute: typeof AuthenticatedSalesResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes/$id': {
      id: '/_authenticated/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof AuthenticatedQuotesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emails/$threadId': {
      id: '/_authenticated/emails/$threadId'
      path: '/emails/$threadId'
      fullPath: '/emails/$threadId'
      preLoaderRoute: typeof AuthenticatedEmailsThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/$id': {
      id: '/_authenticated/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AuthenticatedContactsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies/$id': {
      id: '/_authenticated/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof AuthenticatedCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/gmail/cron-sync': {
      id: '/api/public/gmail/cron-sync'
      path: '/api/public/gmail/cron-sync'
      fullPath: '/api/public/gmail/cron-sync'
      preLoaderRoute: typeof ApiPublicGmailCronSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail/oauth/start': {
      id: '/api/gmail/oauth/start'
      path: '/api/gmail/oauth/start'
      fullPath: '/api/gmail/oauth/start'
      preLoaderRoute: typeof ApiGmailOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail/oauth/callback': {
      id: '/api/gmail/oauth/callback'
      path: '/api/gmail/oauth/callback'
      fullPath: '/api/gmail/oauth/callback'
      preLoaderRoute: typeof ApiGmailOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAgentVisibilityRoute: typeof AuthenticatedSettingsAgentVisibilityRoute
  AuthenticatedSettingsAuditRoute: typeof AuthenticatedSettingsAuditRoute
  AuthenticatedSettingsDashboardStatusRoute: typeof AuthenticatedSettingsDashboardStatusRoute
  AuthenticatedSettingsGmailRoute: typeof AuthenticatedSettingsGmailRoute
  AuthenticatedSettingsOpenaiRoute: typeof AuthenticatedSettingsOpenaiRoute
  AuthenticatedSettingsPermissionsAuditRoute: typeof AuthenticatedSettingsPermissionsAuditRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsRolesRoute: typeof AuthenticatedSettingsRolesRoute
  AuthenticatedSettingsStorageRoute: typeof AuthenticatedSettingsStorageRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAgentVisibilityRoute:
    AuthenticatedSettingsAgentVisibilityRoute,
  AuthenticatedSettingsAuditRoute: AuthenticatedSettingsAuditRoute,
  AuthenticatedSettingsDashboardStatusRoute:
    AuthenticatedSettingsDashboardStatusRoute,
  AuthenticatedSettingsGmailRoute: AuthenticatedSettingsGmailRoute,
  AuthenticatedSettingsOpenaiRoute: AuthenticatedSettingsOpenaiRoute,
  AuthenticatedSettingsPermissionsAuditRoute:
    AuthenticatedSettingsPermissionsAuditRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsRolesRoute: AuthenticatedSettingsRolesRoute,
  AuthenticatedSettingsStorageRoute: AuthenticatedSettingsStorageRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedAiAssistantsRoute: typeof AuthenticatedAiAssistantsRoute
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFollowupsRoute: typeof AuthenticatedFollowupsRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedCompaniesIdRoute: typeof AuthenticatedCompaniesIdRoute
  AuthenticatedContactsIdRoute: typeof AuthenticatedContactsIdRoute
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
  AuthenticatedEmailsThreadIdRoute: typeof AuthenticatedEmailsThreadIdRoute
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedQuotesIdRoute: typeof AuthenticatedQuotesIdRoute
  AuthenticatedSalesResearchRoute: typeof AuthenticatedSalesResearchRoute
  AuthenticatedCompaniesIndexRoute: typeof AuthenticatedCompaniesIndexRoute
  AuthenticatedContactsIndexRoute: typeof AuthenticatedContactsIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedEmailsIndexRoute: typeof AuthenticatedEmailsIndexRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedQuotesIndexRoute: typeof AuthenticatedQuotesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedAiAssistantsRoute: AuthenticatedAiAssistantsRoute,
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFollowupsRoute: AuthenticatedFollowupsRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedCompaniesIdRoute: AuthenticatedCompaniesIdRoute,
  AuthenticatedContactsIdRoute: AuthenticatedContactsIdRoute,
  AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  AuthenticatedEmailsThreadIdRoute: AuthenticatedEmailsThreadIdRoute,
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedQuotesIdRoute: AuthenticatedQuotesIdRoute,
  AuthenticatedSalesResearchRoute: AuthenticatedSalesResearchRoute,
  AuthenticatedCompaniesIndexRoute: AuthenticatedCompaniesIndexRoute,
  AuthenticatedContactsIndexRoute: AuthenticatedContactsIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedEmailsIndexRoute: AuthenticatedEmailsIndexRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedQuotesIndexRoute: AuthenticatedQuotesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiR2UploadRoute: ApiR2UploadRoute,
  ApiGmailDisconnectRoute: ApiGmailDisconnectRoute,
  ApiGmailRefreshBodyRoute: ApiGmailRefreshBodyRoute,
  ApiGmailSendRoute: ApiGmailSendRoute,
  ApiGmailStatusRoute: ApiGmailStatusRoute,
  ApiGmailSyncRoute: ApiGmailSyncRoute,
  ApiGmailOauthCallbackRoute: ApiGmailOauthCallbackRoute,
  ApiGmailOauthStartRoute: ApiGmailOauthStartRoute,
  ApiPublicGmailCronSyncRoute: ApiPublicGmailCronSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
